### ISSUE TITLE
Разделяй и властвуй

### ISSUE THREAD

**Issue by Bobogok** [qurias/react-sneakers#1]
Разделяй и властвуй в информатике — парадигма разработки алгоритмов, заключающаяся в рекурсивном разбиении решаемой задачи на две или более подзадачи того же типа, но меньшего размера, и комбинировании их решений для получения ответа к исходной задаче; разбиения выполняются до тех пор, пока все подзадачи не окажутся элементарными.

Проект - это сложная задача, даже такой маленький как у тебя. Разделяй его на мелкие, более понятные составляющие)🍱

**Comment by qurias** [comment]
Понял, принял твою мысль!
